Upgrade to rails 4, first step.
Now at least can start the server and jump around between pages.

Problems with these gems:

* simple_form - update version to 3.0.0.rc
* friendly_id

friendly_id ~> 5.0.0 supports Rails 4, but it's not available in the
rubygems.org, so had to specify github repo and the alpha1 version.

gem 'friendly_id', '5.0.0.alpha1', github: 'FriendlyId/friendly_id'

The error of friendly_id may look like this:

> NoMethodError - undefined method `synchronize' for nil:NilClass:

* carrierwave

Had to make some changes manually for my PhotoUploader which
inheritents CarrierWave::Uploader::Base.

  class PhotoUploader < CarrierWave::Uploader::Base
    # include Sprockets::Helpers::RailsHelper
    # include Sprockets::Helpers::IsolatedHelper
    include Sprockets::Rails::Helper
  end

Was just copied from the commit:
https://github.com/carrierwaveuploader/carrierwave/issues/661
https://github.com/carrierwaveuploader/carrierwave/commit/c097370cc14901d9378a53cd8c144b89cef5f009

* rails-observers

The error was like this:
Undefined method `cache_sweeper' or uninitialized constant ActionController::Caching::Sweeper

Was issued in https://github.com/rails/rails-observers/issues/4

* protected_attributes
Ran into this error:
uninitialized constant ActiveRecord::MassAssignmentSecurity::NestedAttributes::ClassMethods::REJECT_ALL_BLANK_PROC

https://github.com/rails/protected_attributes/issues/8

Had no time to try those pull requests, so just comment out for now.